#!/usr/bin/env bash
# Copy the browser's form spec into the Worker so both sides share one source
# of truth for field names, labels, roles and options. Run automatically by
# `wrangler deploy` / `wrangler dev` via the [build] hook in wrangler.toml.
set -euo pipefail

cd "$(dirname "$0")"
SRC=../js/forms-config.js
OUT=src/forms-config.generated.js

# Regression guard: this file is served to every visitor. A webhook URL here is
# the bug this Worker exists to fix.
if grep -q "discord.com/api/webhooks" "$SRC"; then
    echo "ERROR: $SRC contains a Discord webhook URL." >&2
    echo "Webhooks belong in Worker secrets only (see worker/README.md)." >&2
    exit 1
fi

{
    echo "/* GENERATED by worker/build.sh from js/forms-config.js — do not edit. */"
    cat "$SRC"
    echo ""
    echo "export { ILLUMENZA_FORMS };"
} > "$OUT"

echo "built $OUT"
